### ISSUE TITLE
WebDav user not created

### ISSUE THREAD

**Issue by vdbhb59** [virtuosoft-dev/hcpp-webdav#1]
I followed all the steps on the plugin first and then on the webdav extension. everything installed correctly, but I can see no WebDav user/account created, nor can I find a way to create one myself. How do I go about it?

![image](https://github.com/user-attachments/assets/281ce3dc-a43c-4799-be61-c4db0ffd1cc2)

**Comment by Steveorevo** [comment]
Internally, this application uses rclone. You should see a unique rclone process for the user accounts in Hestia. Do you see the process via sudo ps -ax ?

**Comment by vdbhb59** [comment]
I can neither see in HestiaCP nor under the Time Command. 😞

**Comment by Steveorevo** [comment]
The “Time command”? This plugin doesn’t create any UI interface. Instead, it simply makes a domain available to mount as a WebDAV for each HestiaCP user in the system. It’s probably not wise to use this plugin in production. I’ll add a disclaimer for that. This plugin is used internally as apart of the “Devstia” (https://github.com/virtuosoft-dev/devstia-app, a localhost server) implementation of HestiaCP on the desktop. 

There are hooks for securing the protocol with at least basic auth and it should ride atop SSL; but that has not been tested for production servers.

**Comment by vdbhb59** [comment]
Ohh, okay. I cannot seem to find a way to uninstall it without breaking my production environment.

**Comment by Steveorevo** [comment]
To remove the hcpp-webdav plugin; you can use the UI drop down in HestiaCP's Config -> Plugins -> WebDAV -> Uninstall, then press the Save button.

**Comment by vdbhb59** [comment]
Closing out now, as there is nothing more to do on this.
